In [3]:
import pandas as pd
from pathlib import Path

In [4]:
# project folders
DATA_DIR = Path("/Users/sasanda/Documents/GitHub/european-soccer-machine-learning/data/extracted")

# file paths
match_path = DATA_DIR / "Match.csv"
team_path = DATA_DIR / "Team.csv"
team_attributes_path = DATA_DIR / "Team_Attributes.csv"
player_path = DATA_DIR / "Player.csv"
player_attributes_path = DATA_DIR / "Player_Attributes.csv"
league_path = DATA_DIR / "League.csv"
country_path = DATA_DIR / "Country.csv"

In [5]:
match = pd.read_csv(match_path)
team = pd.read_csv(team_path)
team_attributes = pd.read_csv(team_attributes_path)
player = pd.read_csv(player_path)
player_attributes = pd.read_csv(player_attributes_path)
league = pd.read_csv(league_path)
country = pd.read_csv(country_path)

## Country table

In [6]:
country.head(10)
country.shape
country.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11 non-null     int64
 1   name    11 non-null     str
dtypes: int64(1), str(1)
memory usage: 308.0 bytes

### Country table conclusion

- The Country table contains country IDs and country names.
- It is a lookup/reference table.
- It does not directly contain predictive features for match outcome.
- It may be useful for identifying the country or league associated with each match.
- Keep for now for joining and interpretation, but it is not expected to be a direct model feature.

## League Table

In [7]:
league.head(10)
league.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          11 non-null     int64
 1   country_id  11 non-null     int64
 2   name        11 non-null     str
dtypes: int64(2), str(1)
memory usage: 396.0 bytes

### League table conclusion

- The League table contains league IDs, country IDs, and league names.
- It connects to the Country table using `country_id`.
- It can be used to identify which league and country each match belongs to.
- It is useful for joining and interpretation.
- League information may later be used as a contextual feature, but the raw IDs should not automatically be used as numerical ML features.

## Match Table

In [8]:
print(match.head(10))

   id  country_id  league_id     season  stage                 date  \
0   1           1          1  2008/2009      1  2008-08-17 00:00:00
1   2           1          1  2008/2009      1  2008-08-16 00:00:00
2   3           1          1  2008/2009      1  2008-08-16 00:00:00
3   4           1          1  2008/2009      1  2008-08-17 00:00:00
4   5           1          1  2008/2009      1  2008-08-16 00:00:00
5   6           1          1  2008/2009      1  2008-09-24 00:00:00
6   7           1          1  2008/2009      1  2008-08-16 00:00:00
7   8           1          1  2008/2009      1  2008-08-16 00:00:00
8   9           1          1  2008/2009      1  2008-08-16 00:00:00
9  10           1          1  2008/2009     10  2008-11-01 00:00:00

   match_api_id  home_team_api_id  away_team_api_id  home_team_goal  ...  \
0        492473              9987              9993               1  ...
1        492474             10000              9994               0  ...
2        492475              9984              8635               0  ...
3        492476              9991              9998               5  ...
4        492477              7947              9985               1  ...
5        492478              8203              8342               1  ...
6        492479              9999              8571               2  ...
7        492480              4049              9996               1  ...
8        492481             10001              9986               1  ...
9        492564              8342              8571               4  ...

     SJA   VCH   VCD   VCA   GBH   GBD    GBA   BSH   BSD   BSA
0   4.00  1.65  3.40  4.50  1.78  3.25   4.00  1.73  3.40  4.20
1   3.80  2.00  3.25  3.25  1.85  3.25   3.75  1.91  3.25  3.60
2   2.50  2.35  3.25  2.65  2.50  3.20   2.50  2.30  3.20  2.75
3   7.50  1.45  3.75  6.50  1.50  3.75   5.50  1.44  3.75  6.50
4   1.73  4.50  3.40  1.65  4.50  3.50   1.65  4.75  3.30  1.67
5   1.67  4.35  3.40  1.70  4.50  3.40   1.70   NaN   NaN   NaN
6   3.60  2.10  3.25  3.00  1.85  3.25   3.75  2.10  3.25  3.10
7   2.40  2.80  3.25  2.25  2.80  3.20   2.25  2.88  3.25  2.20
8   3.10  2.25  3.25  2.80  2.20  3.30   2.80  2.25  3.20  2.80
9  10.00  1.30  4.35  8.50  1.25  5.00  10.00  1.29  4.50  9.00

[10 rows x 115 columns]

In [9]:
match.columns.tolist()

['id',
 'country_id',
 'league_id',
 'season',
 'stage',
 'date',
 'match_api_id',
 'home_team_api_id',
 'away_team_api_id',
 'home_team_goal',
 'away_team_goal',
 'home_player_X1',
 'home_player_X2',
 'home_player_X3',
 'home_player_X4',
 'home_player_X5',
 'home_player_X6',
 'home_player_X7',
 'home_player_X8',
 'home_player_X9',
 'home_player_X10',
 'home_player_X11',
 'away_player_X1',
 'away_player_X2',
 'away_player_X3',
 'away_player_X4',
 'away_player_X5',
 'away_player_X6',
 'away_player_X7',
 'away_player_X8',
 'away_player_X9',
 'away_player_X10',
 'away_player_X11',
 'home_player_Y1',
 'home_player_Y2',
 'home_player_Y3',
 'home_player_Y4',
 'home_player_Y5',
 'home_player_Y6',
 'home_player_Y7',
 'home_player_Y8',
 'home_player_Y9',
 'home_player_Y10',
 'home_player_Y11',
 'away_player_Y1',
 'away_player_Y2',
 'away_player_Y3',
 'away_player_Y4',
 'away_player_Y5',
 'away_player_Y6',
 'away_player_Y7',
 'away_player_Y8',
 'away_player_Y9',
 'away_player_Y10',
 'away_player_Y11',
 'home_player_1',
 'home_player_2',
 'home_player_3',
 'home_player_4',
 'home_player_5',
 'home_player_6',
 'home_player_7',
 'home_player_8',
 'home_player_9',
 'home_player_10',
 'home_player_11',
 'away_player_1',
 'away_player_2',
 'away_player_3',
 'away_player_4',
 'away_player_5',
 'away_player_6',
 'away_player_7',
 'away_player_8',
 'away_player_9',
 'away_player_10',
 'away_player_11',
 'goal',
 'shoton',
 'shotoff',
 'foulcommit',
 'card',
 'cross',
 'corner',
 'possession',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'SJH',
 'SJD',
 'SJA',
 'VCH',
 'VCD',
 'VCA',
 'GBH',
 'GBD',
 'GBA',
 'BSH',
 'BSD',
 'BSA']

In [10]:
# create a copy of the original Match table
match_selected = match.copy()

print("Original shape:", match.shape)
print("Copied shape:", match_selected.shape)

Original shape: (25979, 115)
Copied shape: (25979, 115)

In [11]:
betting_columns = [
    "B365H", "B365D", "B365A",
    "BWH", "BWD", "BWA",
    "IWH", "IWD", "IWA",
    "LBH", "LBD", "LBA",
    "PSH", "PSD", "PSA",
    "WHH", "WHD", "WHA",
    "SJH", "SJD", "SJA",
    "VCH", "VCD", "VCA",
    "GBH", "GBD", "GBA",
    "BSH", "BSD", "BSA"
]
match_selected.drop(
    columns=betting_columns,
    errors="ignore",
    inplace=True
)
print("After removing betting columns:")
print(match_selected.shape)

After removing betting columns:
(25979, 85)

In [12]:
post_match_columns = [
    "goal",
    "shoton",
    "shotoff",
    "foulcommit",
    "card",
    "cross",
    "corner",
    "possession"
]
match_selected.drop(
    columns=post_match_columns,
    errors="ignore",
    inplace=True
)
print("Current Match table shape:", match_selected.shape)
match_selected.columns.tolist()

Current Match table shape: (25979, 77)

['id',
 'country_id',
 'league_id',
 'season',
 'stage',
 'date',
 'match_api_id',
 'home_team_api_id',
 'away_team_api_id',
 'home_team_goal',
 'away_team_goal',
 'home_player_X1',
 'home_player_X2',
 'home_player_X3',
 'home_player_X4',
 'home_player_X5',
 'home_player_X6',
 'home_player_X7',
 'home_player_X8',
 'home_player_X9',
 'home_player_X10',
 'home_player_X11',
 'away_player_X1',
 'away_player_X2',
 'away_player_X3',
 'away_player_X4',
 'away_player_X5',
 'away_player_X6',
 'away_player_X7',
 'away_player_X8',
 'away_player_X9',
 'away_player_X10',
 'away_player_X11',
 'home_player_Y1',
 'home_player_Y2',
 'home_player_Y3',
 'home_player_Y4',
 'home_player_Y5',
 'home_player_Y6',
 'home_player_Y7',
 'home_player_Y8',
 'home_player_Y9',
 'home_player_Y10',
 'home_player_Y11',
 'away_player_Y1',
 'away_player_Y2',
 'away_player_Y3',
 'away_player_Y4',
 'away_player_Y5',
 'away_player_Y6',
 'away_player_Y7',
 'away_player_Y8',
 'away_player_Y9',
 'away_player_Y10',
 'away_player_Y11',
 'home_player_1',
 'home_player_2',
 'home_player_3',
 'home_player_4',
 'home_player_5',
 'home_player_6',
 'home_player_7',
 'home_player_8',
 'home_player_9',
 'home_player_10',
 'home_player_11',
 'away_player_1',
 'away_player_2',
 'away_player_3',
 'away_player_4',
 'away_player_5',
 'away_player_6',
 'away_player_7',
 'away_player_8',
 'away_player_9',
 'away_player_10',
 'away_player_11']

### Match table conclusion

- The Match table is the main table for this project because one row represents one football match.
- It contains the match date, season, stage, league, home team, away team, player IDs, player positions and final goals.
- `home_team_goal` and `away_team_goal` will be used to create the target variable:
  - Home Win
  - Draw
  - Away Win
- `home_team_api_id` and `away_team_api_id` will be used to connect the Match table with the Team and Team_Attributes tables.
- Player IDs can later be connected with Player and Player_Attributes if player-level features are used.
- Betting odds columns were removed because the project is focused on predicting outcomes using team and player performance information rather than bookmaker predictions.
- Post-match event columns such as goals, shots, fouls, cards, corners and possession were removed because they are only known after or during the match and could cause data leakage.
- IDs such as `id` and `match_api_id` are kept temporarily for joining, tracking and debugging, but they are not expected to be final model features.
- The remaining Match table will be used as the base table for building the final machine learning dataset.

## Team

In [13]:
print(team.head(10))
print(team.info())
print(team.isnull().sum())

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB
5   6         8635             229.0     RSC Anderlecht             AND
6   7         9991             674.0           KAA Gent             GEN
7   8         9998            1747.0          RAEC Mons             MON
8   9         7947               NaN      FCV Dender EH             DEN
9  10         9985             232.0  Standard de Liège             STL
<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                299 non-null    int64
 1   team_api_id       299 non-null    int64
 2   team_fifa_api_id  288 non-null    float64
 3   team_long_name    299 non-null    str
 4   team_short_name   299 non-null    str
dtypes: float64(1), int64(2), str(2)
memory usage: 11.8 KB
None
id                   0
team_api_id          0
team_fifa_api_id    11
team_long_name       0
team_short_name      0
dtype: int64

In [14]:
team_selected = team[
    [
        "team_api_id",
        "team_long_name"
    ]
].copy()

team_selected.head(10)

   team_api_id     team_long_name
0         9987           KRC Genk
1         9993       Beerschot AC
2        10000   SV Zulte-Waregem
3         9994   Sporting Lokeren
4         9984  KSV Cercle Brugge
5         8635     RSC Anderlecht
6         9991           KAA Gent
7         9998          RAEC Mons
8         7947      FCV Dender EH
9         9985  Standard de Liège

### Team table conclusion

- The Team table contains 299 football teams.
- `team_api_id` is the important key because it connects teams with `home_team_api_id` and `away_team_api_id` in the Match table.
- `team_long_name` is kept so team IDs can be converted into readable team names.
- `id` was removed because it is only an internal database identifier and is not used by the Match table.
- `team_fifa_api_id` was removed because it is not required for the planned joins and also contains missing values.
- `team_short_name` was removed because the full team name is sufficient for interpretation.
- The reduced Team table will mainly be used as a lookup table when constructing the final match-level dataset.

Decision: Keep the Team table with `team_api_id` and `team_long_name`.

## Team attributes

In [15]:
team_attributes.head(10)

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,NaN,Little,62,Mixed,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,NaN,Little,45,Mixed,...,55,Normal,Organised,42,Medium,42,Press,60,Normal,Cover
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,64.0,Normal,62,Mixed,...,57,Normal,Organised,41,Medium,42,Press,60,Normal,Cover
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,64.0,Normal,53,Mixed,...,63,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,NaN,Little,40,Mixed,...,55,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap

In [16]:
print(team_attributes.shape)
print(team_attributes.info())
print(team_attributes.isnull().sum())
print(team_attributes.columns.tolist())

(1458, 25)
<class 'pandas.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              1458 non-null   int64
 1   team_fifa_api_id                1458 non-null   int64
 2   team_api_id                     1458 non-null   int64
 3   date                            1458 non-null   str
 4   buildUpPlaySpeed                1458 non-null   int64
 5   buildUpPlaySpeedClass           1458 non-null   str
 6   buildUpPlayDribbling            489 non-null    float64
 7   buildUpPlayDribblingClass       1458 non-null   str
 8   buildUpPlayPassing              1458 non-null   int64
 9   buildUpPlayPassingClass         1458 non-null   str
 10  buildUpPlayPositioningClass     1458 non-null   str
 11  chanceCreationPassing           1458 non-null   int64
 12  chanceCreationPassingClass      1458 non-null   str
 13  chanceCreationCrossing          1458 non-null   int64
 14  chanceCreationCrossingClass     1458 non-null   str
 15  chanceCreationShooting          1458 non-null   int64
 16  chanceCreationShootingClass     1458 non-null   str
 17  chanceCreationPositioningClass  1458 non-null   str
 18  defencePressure                 1458 non-null   int64
 19  defencePressureClass            1458 non-null   str
 20  defenceAggression               1458 non-null   int64
 21  defenceAggressionClass          1458 non-null   str
 22  defenceTeamWidth                1458 non-null   int64
 23  defenceTeamWidthClass           1458 non-null   str
 24  defenceDefenderLineClass        1458 non-null   str
dtypes: float64(1), int64(11), str(13)
memory usage: 284.9 KB
None
id                                  0
team_fifa_api_id                    0
team_api_id                         0
date                                0
buildUpPlaySpeed                    0
buildUpPlaySpeedClass               0
buildUpPlayDribbling              969
buildUpPlayDribblingClass           0
buildUpPlayPassing                  0
buildUpPlayPassingClass             0
buildUpPlayPositioningClass         0
chanceCreationPassing               0
chanceCreationPassingClass          0
chanceCreationCrossing              0
chanceCreationCrossingClass         0
chanceCreationShooting              0
chanceCreationShootingClass         0
chanceCreationPositioningClass      0
defencePressure                     0
defencePressureClass                0
defenceAggression                   0
defenceAggressionClass              0
defenceTeamWidth                    0
defenceTeamWidthClass               0
defenceDefenderLineClass            0
dtype: int64
['id', 'team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeed', 'buildUpPlaySpeedClass', 'buildUpPlayDribbling', 'buildUpPlayDribblingClass', 'buildUpPlayPassing', 'buildUpPlayPassingClass', 'buildUpPlayPositioningClass', 'chanceCreationPassing', 'chanceCreationPassingClass', 'chanceCreationCrossing', 'chanceCreationCrossingClass', 'chanceCreationShooting', 'chanceCreationShootingClass', 'chanceCreationPositioningClass', 'defencePressure', 'defencePressureClass', 'defenceAggression', 'defenceAggressionClass', 'defenceTeamWidth', 'defenceTeamWidthClass', 'defenceDefenderLineClass']

In [17]:
team_attributes_selected = team_attributes[
    [
        # join + time
        "team_api_id",
        "date",

        # build-up play
        "buildUpPlaySpeed",
        "buildUpPlayPassing",
        "buildUpPlayDribblingClass",
        "buildUpPlayPositioningClass",

        # chance creation
        "chanceCreationPassing",
        "chanceCreationCrossing",
        "chanceCreationShooting",
        "chanceCreationPositioningClass",

        # defence
        "defencePressure",
        "defenceAggression",
        "defenceTeamWidth",
        "defenceDefenderLineClass"
    ]
].copy()

team_attributes_selected["date"] = pd.to_datetime(
    team_attributes_selected["date"]
)
team_attributes_selected.head()

,team_api_id,date,buildUpPlaySpeed,buildUpPlayPassing,buildUpPlayDribblingClass,buildUpPlayPositioningClass,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,chanceCreationPositioningClass,defencePressure,defenceAggression,defenceTeamWidth,defenceDefenderLineClass
0,9930,2010-02-22,60,50,Little,Organised,60,65,55,Organised,50,55,45,Cover
1,9930,2014-09-19,52,56,Normal,Organised,54,63,64,Organised,47,44,54,Cover
2,9930,2015-09-10,47,54,Normal,Organised,54,63,64,Organised,47,44,54,Cover
3,8485,2010-02-22,70,70,Little,Organised,70,70,70,Organised,60,70,70,Cover
4,8485,2011-02-22,47,52,Little,Organised,53,48,52,Organised,47,47,52,Cover

In [18]:
print(team_attributes_selected.info())
print(team_attributes_selected.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   team_api_id                     1458 non-null   int64
 1   date                            1458 non-null   datetime64[us]
 2   buildUpPlaySpeed                1458 non-null   int64
 3   buildUpPlayPassing              1458 non-null   int64
 4   buildUpPlayDribblingClass       1458 non-null   str
 5   buildUpPlayPositioningClass     1458 non-null   str
 6   chanceCreationPassing           1458 non-null   int64
 7   chanceCreationCrossing          1458 non-null   int64
 8   chanceCreationShooting          1458 non-null   int64
 9   chanceCreationPositioningClass  1458 non-null   str
 10  defencePressure                 1458 non-null   int64
 11  defenceAggression               1458 non-null   int64
 12  defenceTeamWidth                1458 non-null   int64
 13  defenceDefenderLineClass        1458 non-null   str
dtypes: datetime64[us](1), int64(9), str(4)
memory usage: 159.6 KB
None
team_api_id                       0
date                              0
buildUpPlaySpeed                  0
buildUpPlayPassing                0
buildUpPlayDribblingClass         0
buildUpPlayPositioningClass       0
chanceCreationPassing             0
chanceCreationCrossing            0
chanceCreationShooting            0
chanceCreationPositioningClass    0
defencePressure                   0
defenceAggression                 0
defenceTeamWidth                  0
defenceDefenderLineClass          0
dtype: int64

### Team Attributes table conclusion

- The Team_Attributes table contains historical tactical characteristics of each team.
- `team_api_id` is required to connect the table with the home and away teams in the Match table.
- `date` is important because team attributes vary over time. For each match, the latest available team attributes before the match date should be used.
- Numerical features describing build-up play, chance creation and defence were retained as potential predictors.
- Class columns that duplicate numerical variables were removed to avoid redundant features.
- Tactical categorical variables without equivalent numerical features were retained.
- `buildUpPlayDribbling` was removed because it contains a large amount of missing data, while `buildUpPlayDribblingClass` has complete records.
- `id` and `team_fifa_api_id` were removed because they are not required for the planned joins.

Decision: Keep the Team_Attributes table with selected tactical features.

## Player

In [19]:
print(player.info())
player.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 11060 entries, 0 to 11059
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  11060 non-null  int64
 1   player_api_id       11060 non-null  int64
 2   player_name         11060 non-null  str
 3   player_fifa_api_id  11060 non-null  int64
 4   birthday            11060 non-null  str
 5   height              11060 non-null  float64
 6   weight              11060 non-null  int64
dtypes: float64(1), int64(4), str(2)
memory usage: 605.0 KB
None

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
5,6,27316,Aaron Hunt,158138,1986-09-04 00:00:00,182.88,161
6,7,564793,Aaron Kuhl,221280,1996-01-30 00:00:00,172.72,146
7,8,30895,Aaron Lennon,152747,1987-04-16 00:00:00,165.10,139
8,9,528212,Aaron Lennox,206592,1993-02-19 00:00:00,190.50,181
9,10,101042,Aaron Meijers,188621,1987-10-28 00:00:00,175.26,170

In [20]:
player_selected = player[
    [
        "player_api_id",
        "player_name",
        "birthday",
        "height",
        "weight"
    ]
].copy()
player_selected["birthday"] = pd.to_datetime(
    player_selected["birthday"]
)

In [21]:
player_selected.head()

   player_api_id         player_name   birthday  height  weight
0         505942  Aaron Appindangoye 1992-02-29  182.88     187
1         155782     Aaron Cresswell 1989-12-15  170.18     146
2         162549         Aaron Doran 1991-05-13  170.18     163
3          30572       Aaron Galindo 1982-05-08  182.88     198
4          23780        Aaron Hughes 1979-11-08  182.88     154

### Player table conclusion

- The Player table contains 11,060 players and basic player information.
- `player_api_id` is the main key and connects players to the player IDs stored in the Match table.
- `player_name` is retained for interpretation and validation.
- `birthday` is retained because it can be used to calculate a player's age at the date of each match.
- `height` and `weight` are retained as possible player-level features that may later be aggregated at team level.
- `id` and `player_fifa_api_id` were removed because they are not required for the planned joins.

Decision: Keep the Player table with selected player information.

## Player Attributes

In [22]:
print(player_attributes.info())
print(player_attributes.shape)
print(player_attributes.columns.tolist())
player_attributes.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   183978 non-null  int64
 1   player_fifa_api_id   183978 non-null  int64
 2   player_api_id        183978 non-null  int64
 3   date                 183978 non-null  str
 4   overall_rating       183142 non-null  float64
 5   potential            183142 non-null  float64
 6   preferred_foot       183142 non-null  str
 7   attacking_work_rate  177109 non-null  str
 8   defensive_work_rate  183142 non-null  str
 9   crossing             183142 non-null  float64
 10  finishing            183142 non-null  float64
 11  heading_accuracy     183142 non-null  float64
 12  short_passing        183142 non-null  float64
 13  volleys              181265 non-null  float64
 14  dribbling            183142 non-null  float64
 15  curve                181265 non-null  float64
 16  free_kick_accuracy   183142 non-null  float64
 17  long_passing         183142 non-null  float64
 18  ball_control         183142 non-null  float64
 19  acceleration         183142 non-null  float64
 20  sprint_speed         183142 non-null  float64
 21  agility              181265 non-null  float64
 22  reactions            183142 non-null  float64
 23  balance              181265 non-null  float64
 24  shot_power           183142 non-null  float64
 25  jumping              181265 non-null  float64
 26  stamina              183142 non-null  float64
 27  strength             183142 non-null  float64
 28  long_shots           183142 non-null  float64
 29  aggression           183142 non-null  float64
 30  interceptions        183142 non-null  float64
 31  positioning          183142 non-null  float64
 32  vision               181265 non-null  float64
 33  penalties            183142 non-null  float64
 34  marking              183142 non-null  float64
 35  standing_tackle      183142 non-null  float64
 36  sliding_tackle       181265 non-null  float64
 37  gk_diving            183142 non-null  float64
 38  gk_handling          183142 non-null  float64
 39  gk_kicking           183142 non-null  float64
 40  gk_positioning       183142 non-null  float64
 41  gk_reflexes          183142 non-null  float64
dtypes: float64(35), int64(3), str(4)
memory usage: 59.0 MB
None
(183978, 42)
['id', 'player_fifa_api_id', 'player_api_id', 'date', 'overall_rating', 'potential', 'preferred_foot', 'attacking_work_rate', 'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
5,6,189615,155782,2016-04-21 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
6,7,189615,155782,2016-04-07 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
7,8,189615,155782,2016-01-07 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
8,9,189615,155782,2015-12-24 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
9,10,189615,155782,2015-12-17 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0

In [23]:
player_attributes_selected = player_attributes.drop(
    columns=[
        "id",
        "player_fifa_api_id"
    ]
).copy()
player_attributes_selected["date"] = pd.to_datetime(
    player_attributes_selected["date"]
)
print(player_attributes_selected.shape)
player_attributes_selected.head()

(183978, 40)

,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,505942,2016-02-18,67.0,71.0,right,medium,medium,49.0,44.0,71.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,505942,2015-11-19,67.0,71.0,right,medium,medium,49.0,44.0,71.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,505942,2015-09-21,62.0,66.0,right,medium,medium,49.0,44.0,71.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,505942,2015-03-20,61.0,65.0,right,medium,medium,48.0,43.0,70.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,505942,2007-02-22,61.0,65.0,right,medium,medium,48.0,43.0,70.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

### Player Attributes table conclusion

- The Player_Attributes table contains historical football ability ratings for individual players.
- A player can have multiple records because their attributes change over time.
- `player_api_id` is required to connect player records with the player IDs stored in the Match table.
- `date` is essential because only player attributes available before a match should be used. This prevents future information from leaking into the prediction.
- Football ability attributes such as overall rating, passing, finishing, pace, physical ability, defending and goalkeeper skills were retained for now.
- These attributes will not necessarily be used individually in the final dataset. They can later be aggregated into team-level features based on the players participating in each match.
- `id` and `player_fifa_api_id` were removed because they are not required for the planned joins.
- Missing values will be handled later during the preprocessing stage rather than during initial table selection.

Decision: Keep the Player_Attributes table with all relevant historical football attributes.

  .

## Table relationship design

The final machine learning dataset will use the Match table as the base because one row in Match represents one football match.

The other tables will provide additional information about the league, teams and players involved in that match.

Country
   ↓
League
   ↓
Match
 ├──────── Team
 │           ↓
 │     Team_Attributes
 │
 └──────── Players
             ↓
       Player_Attributes

Final unit of analysis:

One row = one match

Final target:

Home Win / Draw / Away Win

In [24]:
home_team_matches = match_selected[
    "home_team_api_id"
].isin(team["team_api_id"]).mean()

away_team_matches = match_selected[
    "away_team_api_id"
].isin(team["team_api_id"]).mean()

print("Home team IDs found in Team:", home_team_matches)
print("Away team IDs found in Team:", away_team_matches)

Home team IDs found in Team: 1.0
Away team IDs found in Team: 1.0

In [25]:
team_attribute_matches = team_attributes_selected[
    "team_api_id"
].isin(team["team_api_id"]).mean()

print(
    "Team Attribute IDs found in Team:",
    team_attribute_matches
)

Team Attribute IDs found in Team: 1.0

In [26]:
home_player_columns = [
    f"home_player_{i}"
    for i in range(1, 12)
]

away_player_columns = [
    f"away_player_{i}"
    for i in range(1, 12)
]

In [27]:
home_players = (
    match_selected[home_player_columns]
    .stack()
    .dropna()
)

home_player_match_rate = home_players.isin(
    player["player_api_id"]
).mean()

print(
    "Home player IDs found in Player:",
    home_player_match_rate
)

Home player IDs found in Player: 1.0

In [28]:
away_players = (
    match_selected[away_player_columns]
    .stack()
    .dropna()
)

away_player_match_rate = away_players.isin(
    player["player_api_id"]
).mean()

print(
    "Away player IDs found in Player:",
    away_player_match_rate
)

Away player IDs found in Player: 1.0

In [29]:
player_attribute_match_rate = (
    player_attributes_selected["player_api_id"]
    .isin(player["player_api_id"])
    .mean()
)

print(
    "Player Attribute IDs found in Player:",
    player_attribute_match_rate
)

Player Attribute IDs found in Player: 1.0

In [30]:
match_base = match_selected.copy()

match_base["date"] = pd.to_datetime(match_base["date"])

print(match_base.shape)
match_base.head()

(25979, 77)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11
0,1,1,1,2008/2009,1,2008-08-17,492473,9987,9993,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,1,2008/2009,1,2008-08-16,492474,10000,9994,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,1,2008/2009,1,2008-08-16,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,2008/2009,1,2008-08-17,492476,9991,9998,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,1,2008/2009,1,2008-08-16,492477,7947,9985,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
def create_result(row):
    if row["home_team_goal"] > row["away_team_goal"]:
        return "Home Win"
    elif row["home_team_goal"] < row["away_team_goal"]:
        return "Away Win"
    else:
        return "Draw"


match_base["target"] = match_base.apply(
    create_result,
    axis=1
)

In [32]:
match_base["target"].value_counts()

target
Home Win    11917
Away Win     7466
Draw         6596
Name: count, dtype: int64

In [33]:
match_base["target"].value_counts(normalize=True) * 100

target
Home Win    45.871666
Away Win    28.738597
Draw        25.389738
Name: proportion, dtype: float64

In [34]:
country_lookup = country[
    ["id", "name"]
].rename(
    columns={
        "id": "country_id",
        "name": "country_name"
    }
)

In [35]:
match_base = match_base.merge(
    country_lookup,
    on="country_id",
    how="left"
)

In [36]:
league_lookup = league[
    ["id", "name"]
].rename(
    columns={
        "id": "league_id",
        "name": "league_name"
    }
)

In [37]:
match_base = match_base.merge(
    league_lookup,
    on="league_id",
    how="left"
)

In [38]:
home_team_lookup = team_selected.rename(
    columns={
        "team_api_id": "home_team_api_id",
        "team_long_name": "home_team_name"
    }
)

In [39]:
match_base = match_base.merge(
    home_team_lookup,
    on="home_team_api_id",
    how="left"
)

In [40]:
away_team_lookup = team_selected.rename(
    columns={
        "team_api_id": "away_team_api_id",
        "team_long_name": "away_team_name"
    }
)

In [41]:
match_base = match_base.merge(
    away_team_lookup,
    on="away_team_api_id",
    how="left"
)

In [42]:
basic_columns = [
    "date",
    "season",
    "stage",
    "country_name",
    "league_name",
    "home_team_name",
    "away_team_name",
    "home_team_goal",
    "away_team_goal",
    "target"
]

match_base[basic_columns].head(10)

,date,season,stage,country_name,league_name,home_team_name,away_team_name,home_team_goal,away_team_goal,target
0,2008-08-17,2008/2009,1,Belgium,Belgium Jupiler League,KRC Genk,Beerschot AC,1,1,Draw
1,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,SV Zulte-Waregem,Sporting Lokeren,0,0,Draw
2,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,KSV Cercle Brugge,RSC Anderlecht,0,3,Away Win
3,2008-08-17,2008/2009,1,Belgium,Belgium Jupiler League,KAA Gent,RAEC Mons,5,0,Home Win
4,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,FCV Dender EH,Standard de Liège,1,3,Away Win
5,2008-09-24,2008/2009,1,Belgium,Belgium Jupiler League,KV Mechelen,Club Brugge KV,1,1,Draw
6,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,KSV Roeselare,KV Kortrijk,2,2,Draw
7,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,Tubize,Royal Excel Mouscron,1,2,Away Win
8,2008-08-16,2008/2009,1,Belgium,Belgium Jupiler League,KVC Westerlo,Sporting Charleroi,1,0,Home Win
9,2008-11-01,2008/2009,10,Belgium,Belgium Jupiler League,Club Brugge KV,KV Kortrijk,4,1,Home Win

In [43]:
print("Rows:", len(match_base))
print("Duplicate rows:", match_base["id"].duplicated().sum())

Rows: 25979
Duplicate rows: 0

In [44]:
match_base[
    [
        "country_name",
        "league_name",
        "home_team_name",
        "away_team_name"
    ]
].isnull().sum()

country_name      0
league_name       0
home_team_name    0
away_team_name    0
dtype: int64

Adding historical Team_Attributes to every match

In [45]:
# make sure dates are datetime
match_base["date"] = pd.to_datetime(match_base["date"])

team_attributes_selected["date"] = pd.to_datetime(
    team_attributes_selected["date"]
)

In [46]:
home_team_attributes = team_attributes_selected.copy()

home_team_attributes = home_team_attributes.rename(
    columns={
        "team_api_id": "home_team_api_id",
        "date": "home_team_attr_date"
    }
)

# add "home_" to all actual feature columns
home_team_attributes = home_team_attributes.rename(
    columns={
        col: f"home_{col}"
        for col in home_team_attributes.columns
        if col not in ["home_team_api_id", "home_team_attr_date"]
    }
)

In [47]:
home_team_attributes.head()

,home_team_api_id,home_team_attr_date,home_buildUpPlaySpeed,home_buildUpPlayPassing,home_buildUpPlayDribblingClass,home_buildUpPlayPositioningClass,home_chanceCreationPassing,home_chanceCreationCrossing,home_chanceCreationShooting,home_chanceCreationPositioningClass,home_defencePressure,home_defenceAggression,home_defenceTeamWidth,home_defenceDefenderLineClass
0,9930,2010-02-22,60,50,Little,Organised,60,65,55,Organised,50,55,45,Cover
1,9930,2014-09-19,52,56,Normal,Organised,54,63,64,Organised,47,44,54,Cover
2,9930,2015-09-10,47,54,Normal,Organised,54,63,64,Organised,47,44,54,Cover
3,8485,2010-02-22,70,70,Little,Organised,70,70,70,Organised,60,70,70,Cover
4,8485,2011-02-22,47,52,Little,Organised,53,48,52,Organised,47,47,52,Cover

In [48]:
match_base = match_base.sort_values(
    ["date", "home_team_api_id"]
).reset_index(drop=True)

home_team_attributes = home_team_attributes.sort_values(
    ["home_team_attr_date", "home_team_api_id"]
).reset_index(drop=True)

In [49]:
match_with_team_attrs = pd.merge_asof(
    match_base,
    home_team_attributes,

    left_on="date",
    right_on="home_team_attr_date",

    left_by="home_team_api_id",
    right_by="home_team_api_id",

    direction="backward"
)

In [50]:
match_with_team_attrs[
    [
        "date",
        "home_team_name",
        "home_team_attr_date",
        "home_buildUpPlaySpeed",
        "home_chanceCreationShooting",
        "home_defencePressure"
    ]
].head(20)

,date,home_team_name,home_team_attr_date,home_buildUpPlaySpeed,home_chanceCreationShooting,home_defencePressure
0,2008-07-18,BSC Young Boys,NaT,NaN,NaN,NaN
1,2008-07-19,FC Aarau,NaT,NaN,NaN,NaN
2,2008-07-20,Neuchâtel Xamax,NaT,NaN,NaN,NaN
3,2008-07-20,FC Luzern,NaT,NaN,NaN,NaN
4,2008-07-23,AC Bellinzona,NaT,NaN,NaN,NaN
5,2008-07-23,FC Basel,NaT,NaN,NaN,NaN
6,2008-07-23,FC Zürich,NaT,NaN,NaN,NaN
7,2008-07-24,FC Vaduz,NaT,NaN,NaN,NaN
8,2008-07-24,FC Sion,NaT,NaN,NaN,NaN
9,2008-07-26,FC Basel,NaT,NaN,NaN,NaN
10,2008-07-26,FC Luzern,NaT,NaN,NaN,NaN
11,2008-07-27,FC Aarau,NaT,NaN,NaN,NaN
12,2008-07-27,BSC Young Boys,NaT,NaN,NaN,NaN
13,2008-07-30,Grasshopper Club Zürich,NaT,NaN,NaN,NaN
14,2008-08-02,Neuchâtel Xamax,NaT,NaN,NaN,NaN
15,2008-08-02,FC Sion,NaT,NaN,NaN,NaN
16,2008-08-03,AC Bellinzona,NaT,NaN,NaN,NaN
17,2008-08-03,FC Vaduz,NaT,NaN,NaN,NaN
18,2008-08-03,FC Zürich,NaT,NaN,NaN,NaN
19,2008-08-06,AC Bellinzona,NaT,NaN,NaN,NaN

In [51]:
(
    match_with_team_attrs["home_team_attr_date"]
    > match_with_team_attrs["date"]
).sum()

np.int64(0)

In [52]:
away_team_attributes = team_attributes_selected.copy()

away_team_attributes = away_team_attributes.rename(
    columns={
        "team_api_id": "away_team_api_id",
        "date": "away_team_attr_date"
    }
)

away_team_attributes = away_team_attributes.rename(
    columns={
        col: f"away_{col}"
        for col in away_team_attributes.columns
        if col not in ["away_team_api_id", "away_team_attr_date"]
    }
)

In [53]:
match_with_team_attrs = match_with_team_attrs.sort_values(
    ["date", "away_team_api_id"]
).reset_index(drop=True)

away_team_attributes = away_team_attributes.sort_values(
    ["away_team_attr_date", "away_team_api_id"]
).reset_index(drop=True)

In [54]:
match_with_team_attrs = pd.merge_asof(
    match_with_team_attrs,
    away_team_attributes,

    left_on="date",
    right_on="away_team_attr_date",

    left_by="away_team_api_id",
    right_by="away_team_api_id",

    direction="backward"
)

In [55]:
columns_to_view = [
    "date",
    "home_team_name",
    "away_team_name",

    "home_buildUpPlaySpeed",
    "away_buildUpPlaySpeed",

    "home_chanceCreationShooting",
    "away_chanceCreationShooting",

    "home_defencePressure",
    "away_defencePressure",

    "target"
]

match_with_team_attrs[columns_to_view].head(20)

,date,home_team_name,away_team_name,home_buildUpPlaySpeed,away_buildUpPlaySpeed,home_chanceCreationShooting,away_chanceCreationShooting,home_defencePressure,away_defencePressure,target
0,2008-07-18,BSC Young Boys,FC Basel,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
1,2008-07-19,FC Aarau,FC Sion,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
2,2008-07-20,FC Luzern,FC Vaduz,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
3,2008-07-20,Neuchâtel Xamax,FC Zürich,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
4,2008-07-23,AC Bellinzona,Neuchâtel Xamax,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
5,2008-07-23,FC Basel,Grasshopper Club Zürich,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
6,2008-07-23,FC Zürich,FC Luzern,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
7,2008-07-24,FC Vaduz,FC Aarau,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
8,2008-07-24,FC Sion,BSC Young Boys,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
9,2008-07-26,FC Basel,AC Bellinzona,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
10,2008-07-26,FC Luzern,Neuchâtel Xamax,NaN,NaN,NaN,NaN,NaN,NaN,Away Win
11,2008-07-27,BSC Young Boys,FC Vaduz,NaN,NaN,NaN,NaN,NaN,NaN,Draw
12,2008-07-27,FC Aarau,FC Zürich,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
13,2008-07-30,Grasshopper Club Zürich,FC Sion,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
14,2008-08-02,Neuchâtel Xamax,FC Aarau,NaN,NaN,NaN,NaN,NaN,NaN,Draw
15,2008-08-02,FC Sion,FC Basel,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
16,2008-08-03,FC Vaduz,Grasshopper Club Zürich,NaN,NaN,NaN,NaN,NaN,NaN,Draw
17,2008-08-03,FC Zürich,BSC Young Boys,NaN,NaN,NaN,NaN,NaN,NaN,Home Win
18,2008-08-03,AC Bellinzona,FC Luzern,NaN,NaN,NaN,NaN,NaN,NaN,Draw
19,2008-08-06,AC Bellinzona,FC Aarau,NaN,NaN,NaN,NaN,NaN,NaN,Draw

In [56]:
print(
    "Missing home team attributes:",
    match_with_team_attrs["home_buildUpPlaySpeed"].isnull().sum()
)

print(
    "Missing away team attributes:",
    match_with_team_attrs["away_buildUpPlaySpeed"].isnull().sum()
)

Missing home team attributes: 6063
Missing away team attributes: 6055

In [57]:
print("Rows:", len(match_with_team_attrs))
print(
    "Duplicate match IDs:",
    match_with_team_attrs["id"].duplicated().sum()
)

Rows: 25979
Duplicate match IDs: 0

In [58]:
print("Match date range:")
print(match_base["date"].min(), "to", match_base["date"].max())

print("\nTeam attributes date range:")
print(
    team_attributes_selected["date"].min(),
    "to",
    team_attributes_selected["date"].max()
)

Match date range:
2008-07-18 00:00:00 to 2016-05-25 00:00:00

Team attributes date range:
2010-02-22 00:00:00 to 2015-09-10 00:00:00

In [59]:
home_missing = match_with_team_attrs["home_buildUpPlaySpeed"].isnull()
away_missing = match_with_team_attrs["away_buildUpPlaySpeed"].isnull()

print("Missing home:", home_missing.sum())
print("Missing away:", away_missing.sum())

print(
    "Both missing:",
    (home_missing & away_missing).sum()
)

print(
    "Only home missing:",
    (home_missing & ~away_missing).sum()
)

print(
    "Only away missing:",
    (~home_missing & away_missing).sum()
)

print(
    "At least one missing:",
    (home_missing | away_missing).sum()
)

Missing home: 6063
Missing away: 6055
Both missing: 5494
Only home missing: 569
Only away missing: 561
At least one missing: 6624

In [60]:
print("Match date range:")
print(match_base["date"].min(), "to", match_base["date"].max())

print("\nTeam attributes date range:")
print(
    team_attributes_selected["date"].min(),
    "to",
    team_attributes_selected["date"].max()
)

Match date range:
2008-07-18 00:00:00 to 2016-05-25 00:00:00

Team attributes date range:
2010-02-22 00:00:00 to 2015-09-10 00:00:00

In [61]:
home_missing = match_with_team_attrs["home_buildUpPlaySpeed"].isnull()
away_missing = match_with_team_attrs["away_buildUpPlaySpeed"].isnull()

print("Missing home:", home_missing.sum())
print("Missing away:", away_missing.sum())

print(
    "Both missing:",
    (home_missing & away_missing).sum()
)

print(
    "Only home missing:",
    (home_missing & ~away_missing).sum()
)

print(
    "Only away missing:",
    (~home_missing & away_missing).sum()
)

print(
    "At least one missing:",
    (home_missing | away_missing).sum()
)

Missing home: 6063
Missing away: 6055
Both missing: 5494
Only home missing: 569
Only away missing: 561
At least one missing: 6624

In [62]:
missing_by_season = (
    match_with_team_attrs
    .assign(
        missing_team_attributes=home_missing | away_missing
    )
    .groupby("season")["missing_team_attributes"]
    .agg(["sum", "count"])
)

missing_by_season["percentage"] = (
    missing_by_season["sum"]
    / missing_by_season["count"]
    * 100
)

missing_by_season

            sum  count  percentage
season
2008/2009  3326   3326  100.000000
2009/2010  2143   3230   66.346749
2010/2011   211   3260    6.472393
2011/2012   143   3220    4.440994
2012/2013   225   3260    6.901840
2013/2014   189   3032    6.233509
2014/2015   231   3325    6.947368
2015/2016   156   3326    4.690319

In [63]:
model_data = match_with_team_attrs[
    match_with_team_attrs["season"].isin([
        "2010/2011",
        "2011/2012",
        "2012/2013",
        "2013/2014",
        "2014/2015",
        "2015/2016"
    ])
].copy()

print("Matches kept:", len(model_data))

Matches kept: 19423

In [64]:
team_attribute_check_columns = [
    "home_buildUpPlaySpeed",
    "away_buildUpPlaySpeed"
]

model_data = model_data.dropna(
    subset=team_attribute_check_columns
).copy()

print("Matches remaining:", len(model_data))

Matches remaining: 18268

In [65]:
print(
    "Missing home:",
    model_data["home_buildUpPlaySpeed"].isnull().sum()
)

print(
    "Missing away:",
    model_data["away_buildUpPlaySpeed"].isnull().sum()
)

print(
    "Duplicate matches:",
    model_data["id"].duplicated().sum()
)

Missing home: 0
Missing away: 0
Duplicate matches: 0

In [66]:
match_with_team_attrs["target"].value_counts(normalize=True) * 100

target
Home Win    45.871666
Away Win    28.738597
Draw        25.389738
Name: proportion, dtype: float64

In [67]:
model_data["target"].value_counts(normalize=True) * 100

target
Home Win    45.538647
Away Win    29.094592
Draw        25.366762
Name: proportion, dtype: float64

### Team attribute coverage decision

The match dataset covers 2008/2009 to 2015/2016, while the Team_Attributes table begins on 22 February 2010.

As a result:

- 2008/2009 has no historical team attribute information.
- 2009/2010 contains only partial team attribute coverage.
- Seasons from 2010/2011 onward have much higher coverage.

To avoid using future team information and causing data leakage, the modelling dataset was restricted to complete seasons from 2010/2011 to 2015/2016.

Matches where either the home or away team still had no historical Team_Attributes record were excluded rather than imputing artificial tactical values.

This produces a cleaner dataset where team attributes represent information that was genuinely available before each match.

### Recent team form

In [68]:
# We calculate form from ALL historical matches
history_source = match_base[
    [
        "id",
        "date",
        "home_team_api_id",
        "away_team_api_id",
        "home_team_goal",
        "away_team_goal"
    ]
].copy()

history_source["date"] = pd.to_datetime(history_source["date"])

In [69]:
home_history = history_source[
    [
        "id",
        "date",
        "home_team_api_id",
        "away_team_api_id",
        "home_team_goal",
        "away_team_goal"
    ]
].copy()

home_history.columns = [
    "match_id",
    "date",
    "team_api_id",
    "opponent_api_id",
    "goals_for",
    "goals_against"
]

In [70]:
away_history = history_source[
    [
        "id",
        "date",
        "away_team_api_id",
        "home_team_api_id",
        "away_team_goal",
        "home_team_goal"
    ]
].copy()

away_history.columns = [
    "match_id",
    "date",
    "team_api_id",
    "opponent_api_id",
    "goals_for",
    "goals_against"
]

In [71]:
team_history = pd.concat(
    [home_history, away_history],
    ignore_index=True
)

team_history.head()

   match_id       date  team_api_id  opponent_api_id  goals_for  goals_against
0     24559 2008-07-18        10192             9931          1              2
1     24560 2008-07-19         9930            10179          3              1
2     24562 2008-07-20         7955            10243          1              2
3     24561 2008-07-20        10199             9824          1              2
4     24614 2008-07-23         6493             7955          1              2

In [72]:
team_history.shape

(51958, 6)

In [73]:
def calculate_points(row):
    if row["goals_for"] > row["goals_against"]:
        return 3
    elif row["goals_for"] == row["goals_against"]:
        return 1
    else:
        return 0


team_history["points"] = team_history.apply(
    calculate_points,
    axis=1
)

In [74]:
team_history[
    [
        "team_api_id",
        "date",
        "goals_for",
        "goals_against",
        "points"
    ]
].head(10)

   team_api_id       date  goals_for  goals_against  points
0        10192 2008-07-18          1              2       0
1         9930 2008-07-19          3              1       3
2         7955 2008-07-20          1              2       0
3        10199 2008-07-20          1              2       0
4         6493 2008-07-23          1              2       0
5         9931 2008-07-23          1              0       3
6        10243 2008-07-23          1              0       3
7         9824 2008-07-24          0              2       0
8        10179 2008-07-24          2              1       3
9         9931 2008-07-26          2              0       3

In [75]:
team_history = team_history.sort_values(
    ["team_api_id", "date", "match_id"]
).reset_index(drop=True)

In [76]:
team_history["form_points_5"] = (
    team_history
    .groupby("team_api_id")["points"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=5,
            min_periods=5
        ).sum()
    )
)

In [77]:
team_history["avg_goals_scored_5"] = (
    team_history
    .groupby("team_api_id")["goals_for"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=5,
            min_periods=5
        ).mean()
    )
)

In [78]:
team_history["avg_goals_conceded_5"] = (
    team_history
    .groupby("team_api_id")["goals_against"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=5,
            min_periods=5
        ).mean()
    )
)

In [79]:
example_team = team_history["team_api_id"].iloc[0]

team_history[
    team_history["team_api_id"] == example_team
][
    [
        "date",
        "goals_for",
        "goals_against",
        "points",
        "form_points_5",
        "avg_goals_scored_5",
        "avg_goals_conceded_5"
    ]
].head(12)

,date,goals_for,goals_against,points,form_points_5,avg_goals_scored_5,avg_goals_conceded_5
0,2008-08-10,0,0,1,NaN,NaN,NaN
1,2008-08-16,2,1,3,NaN,NaN,NaN
2,2008-08-22,2,1,3,NaN,NaN,NaN
3,2008-08-30,0,3,0,NaN,NaN,NaN
4,2008-09-12,2,0,3,NaN,NaN,NaN
5,2008-09-20,0,3,0,10.0,1.2,1.0
6,2008-09-27,0,0,1,9.0,1.2,1.6
7,2008-10-04,0,1,0,7.0,0.8,1.4
8,2008-10-19,2,0,3,4.0,0.4,1.4
9,2008-10-24,0,0,1,7.0,0.8,0.8
10,2008-11-02,0,2,0,5.0,0.4,0.8
11,2008-11-08,0,0,1,5.0,0.4,0.6

In [80]:
home_form = team_history[
    [
        "match_id",
        "team_api_id",
        "form_points_5",
        "avg_goals_scored_5",
        "avg_goals_conceded_5"
    ]
].copy()

In [81]:
home_form = home_form.rename(
    columns={
        "team_api_id": "home_team_api_id",
        "form_points_5": "home_form_points_5",
        "avg_goals_scored_5": "home_avg_goals_scored_5",
        "avg_goals_conceded_5": "home_avg_goals_conceded_5"
    }
)

In [82]:
model_data = model_data.merge(
    home_form,
    left_on=["id", "home_team_api_id"],
    right_on=["match_id", "home_team_api_id"],
    how="left"
)

model_data.drop(
    columns=["match_id"],
    inplace=True
)

In [83]:
away_form = team_history[
    [
        "match_id",
        "team_api_id",
        "form_points_5",
        "avg_goals_scored_5",
        "avg_goals_conceded_5"
    ]
].copy()

away_form = away_form.rename(
    columns={
        "team_api_id": "away_team_api_id",
        "form_points_5": "away_form_points_5",
        "avg_goals_scored_5": "away_avg_goals_scored_5",
        "avg_goals_conceded_5": "away_avg_goals_conceded_5"
    }
)

In [84]:
model_data = model_data.merge(
    away_form,
    left_on=["id", "away_team_api_id"],
    right_on=["match_id", "away_team_api_id"],
    how="left"
)

model_data.drop(
    columns=["match_id"],
    inplace=True
)

In [85]:
form_columns = [
    "date",
    "home_team_name",
    "away_team_name",

    "home_form_points_5",
    "away_form_points_5",

    "home_avg_goals_scored_5",
    "away_avg_goals_scored_5",

    "home_avg_goals_conceded_5",
    "away_avg_goals_conceded_5",

    "target"
]

model_data[form_columns].head(20)

,date,home_team_name,away_team_name,home_form_points_5,away_form_points_5,home_avg_goals_scored_5,away_avg_goals_scored_5,home_avg_goals_conceded_5,away_avg_goals_conceded_5,target
0,2010-07-17,Grasshopper Club Zürich,Neuchâtel Xamax,9.0,4.0,2.4,1.8,0.6,2.6,Draw
1,2010-07-18,AC Bellinzona,FC Sion,7.0,6.0,1.0,1.6,1.6,1.8,Away Win
2,2010-07-18,FC Luzern,FC St. Gallen,13.0,3.0,2.8,1.0,0.4,2.4,Home Win
3,2010-07-20,FC Basel,FC Zürich,12.0,4.0,2.4,1.2,0.8,2.6,Home Win
4,2010-07-24,FC Sion,FC Basel,9.0,15.0,1.8,3.0,1.4,0.4,Away Win
5,2010-07-24,BSC Young Boys,FC Luzern,7.0,13.0,1.2,2.8,1.8,0.2,Draw
6,2010-07-25,FC St. Gallen,AC Bellinzona,3.0,4.0,1.0,0.6,2.8,1.8,Home Win
7,2010-07-25,FC Zürich,Grasshopper Club Zürich,4.0,7.0,1.4,1.8,2.4,0.8,Home Win
8,2010-07-30,Standard de Liège,SV Zulte-Waregem,4.0,4.0,0.6,0.8,1.2,1.0,Draw
9,2010-07-31,KV Kortrijk,Club Brugge KV,11.0,11.0,2.0,1.8,0.8,0.8,Home Win
10,2010-07-31,KVC Westerlo,KAA Gent,7.0,8.0,1.2,1.2,0.6,0.8,Away Win
11,2010-07-31,KV Mechelen,Sporting Lokeren,7.0,3.0,1.2,0.6,1.4,3.0,Home Win
12,2010-07-31,FC Zürich,FC Sion,7.0,6.0,1.8,1.8,2.0,1.8,Draw
13,2010-07-31,AC Bellinzona,BSC Young Boys,4.0,5.0,1.0,1.0,1.6,2.0,Home Win
14,2010-08-01,FC Luzern,Neuchâtel Xamax,11.0,5.0,2.2,2.0,0.4,2.2,Home Win
15,2010-08-01,KSV Cercle Brugge,Sporting Charleroi,12.0,4.0,2.0,1.0,0.6,1.2,Draw
16,2010-08-01,KRC Genk,Beerschot AC,2.0,3.0,0.6,0.8,1.4,1.8,Home Win
17,2010-08-01,FC Basel,FC St. Gallen,15.0,3.0,2.6,1.2,0.6,3.0,Home Win
18,2010-08-06,Polonia Bytom,P. Warszawa,7.0,10.0,0.8,1.0,0.6,0.4,Away Win
19,2010-08-06,GKS Bełchatów,Polonia Bytom,8.0,7.0,1.6,0.8,1.0,1.2,Home Win

In [86]:
form_feature_columns = [
    "home_form_points_5",
    "away_form_points_5",
    "home_avg_goals_scored_5",
    "away_avg_goals_scored_5",
    "home_avg_goals_conceded_5",
    "away_avg_goals_conceded_5"
]
model_data[form_feature_columns].isnull().sum()

home_form_points_5           127
away_form_points_5           132
home_avg_goals_scored_5      127
away_avg_goals_scored_5      132
home_avg_goals_conceded_5    127
away_avg_goals_conceded_5    132
dtype: int64

In [87]:
missing_form_rows = model_data[
    form_feature_columns
].isnull().any(axis=1).sum()

print("Matches without complete previous-5 form:", missing_form_rows)

print(
    "Percentage:",
    missing_form_rows / len(model_data) * 100
)

Matches without complete previous-5 form: 252
Percentage: 1.3794613531858988

In [88]:
print("Rows:", len(model_data))
print(
    "Duplicate match IDs:",
    model_data["id"].duplicated().sum()
)

Rows: 18268
Duplicate match IDs: 0

In [89]:
model_data = model_data.dropna(
    subset=form_feature_columns
).copy()

print("Rows remaining:", len(model_data))
print("Duplicate match IDs:", model_data["id"].duplicated().sum())

Rows remaining: 18016
Duplicate match IDs: 0

In [90]:
model_data["target"].value_counts(normalize=True) * 100

target
Home Win    45.609458
Away Win    29.063055
Draw        25.327487
Name: proportion, dtype: float64

### Recent-form feature decision

Recent team performance was calculated using each team's previous five matches.

The following features were created:

- points earned in the previous five matches
- average goals scored in the previous five matches
- average goals conceded in the previous five matches

The current match was excluded from all calculations using a one-match shift to prevent data leakage.

252 matches (approximately 1.38% of the modelling dataset) did not have a complete five-match history for both teams. These matches were removed instead of imputing artificial recent-form values.

After this step, 18,016 matches remained.

## Player strength.

In [91]:
pa = player_attributes_selected.copy()

In [92]:
pa["attack_score"] = pa[
    [
        "finishing",
        "shot_power",
        "long_shots",
        "positioning"
    ]
].mean(axis=1)

In [93]:
pa["passing_score"] = pa[
    [
        "short_passing",
        "long_passing",
        "vision"
    ]
].mean(axis=1)

In [94]:
pa["technical_score"] = pa[
    [
        "dribbling",
        "ball_control"
    ]
].mean(axis=1)

In [95]:
pa["pace_score"] = pa[
    [
        "acceleration",
        "sprint_speed",
        "agility"
    ]
].mean(axis=1)

In [96]:
pa["physical_score"] = pa[
    [
        "stamina",
        "strength",
        "jumping",
        "aggression"
    ]
].mean(axis=1)

In [97]:
pa["defence_score"] = pa[
    [
        "interceptions",
        "marking",
        "standing_tackle",
        "sliding_tackle"
    ]
].mean(axis=1)

In [98]:
pa["goalkeeper_score"] = pa[
    [
        "gk_diving",
        "gk_handling",
        "gk_kicking",
        "gk_positioning",
        "gk_reflexes"
    ]
].mean(axis=1)

In [99]:
player_features = pa[
    [
        "player_api_id",
        "date",
        "overall_rating",
        "potential",
        "attack_score",
        "passing_score",
        "technical_score",
        "pace_score",
        "physical_score",
        "defence_score",
        "goalkeeper_score"
    ]
].copy()

In [100]:
player_features["date"] = pd.to_datetime(
    player_features["date"]
)

In [101]:
player_features.head()

,player_api_id,date,overall_rating,potential,attack_score,passing_score,technical_score,pace_score,physical_score,defence_score,goalkeeper_score
0,505942,2016-02-18,67.0,71.0,44.75,59.666667,50.0,61.0,64.75,68.25,8.6
1,505942,2015-11-19,67.0,71.0,44.75,59.666667,50.0,61.0,64.75,68.25,8.6
2,505942,2015-09-21,62.0,66.0,44.75,59.666667,50.0,61.0,62.75,60.25,8.6
3,505942,2015-03-20,61.0,65.0,43.75,58.666667,49.0,61.0,62.50,57.75,7.6
4,505942,2007-02-22,61.0,65.0,43.75,58.666667,49.0,61.0,62.50,57.75,7.6

In [102]:
player_features.shape

(183978, 11)

In [103]:
home_player_cols = [f"home_player_{i}" for i in range(1, 12)]
away_player_cols = [f"away_player_{i}" for i in range(1, 12)]

lineup_check = model_data[["id"]].copy()

lineup_check["home_players_available"] = (
    model_data[home_player_cols].notna().sum(axis=1)
)

lineup_check["away_players_available"] = (
    model_data[away_player_cols].notna().sum(axis=1)
)

lineup_check[
    ["home_players_available", "away_players_available"]
].describe()

       home_players_available  away_players_available
count            18016.000000            18016.000000
mean                10.838477               10.834813
std                  0.766056                0.777722
min                  2.000000                2.000000
25%                 11.000000               11.000000
50%                 11.000000               11.000000
75%                 11.000000               11.000000
max                 11.000000               11.000000

In [104]:
print(
    "Full home lineups:",
    (lineup_check["home_players_available"] == 11).sum()
)

print(
    "Full away lineups:",
    (lineup_check["away_players_available"] == 11).sum()
)

Full home lineups: 16741
Full away lineups: 16717

In [105]:
home_players_long = model_data[
    ["id", "date"] + home_player_cols
].melt(
    id_vars=["id", "date"],
    value_vars=home_player_cols,
    var_name="player_slot",
    value_name="player_api_id"
)

home_players_long["side"] = "home"

In [106]:
away_players_long = model_data[
    ["id", "date"] + away_player_cols
].melt(
    id_vars=["id", "date"],
    value_vars=away_player_cols,
    var_name="player_slot",
    value_name="player_api_id"
)

away_players_long["side"] = "away"

In [107]:
players_long = pd.concat(
    [home_players_long, away_players_long],
    ignore_index=True
)

In [108]:
players_long = players_long.dropna(
    subset=["player_api_id"]
).copy()

players_long["player_api_id"] = (
    players_long["player_api_id"].astype("int64")
)

In [109]:
players_long.head()

      id       date    player_slot  player_api_id  side
0  24918 2010-07-17  home_player_1          67374  home
1  24920 2010-07-18  home_player_1          42259  home
2  24921 2010-07-18  home_player_1          42276  home
3  24922 2010-07-20  home_player_1          41618  home
4  24973 2010-07-24  home_player_1          10637  home

In [110]:
player_features_join = player_features.copy()

player_features_join = player_features_join.rename(
    columns={
        "date": "attribute_date"
    }
)

In [111]:
print(
    "Duplicate player/date rows:",
    player_features_join.duplicated(
        subset=["player_api_id", "attribute_date"]
    ).sum()
)

Duplicate player/date rows: 836

In [112]:
player_features_join = (
    player_features_join
    .drop_duplicates(
        subset=["player_api_id", "attribute_date"],
        keep="last"
    )
)

In [113]:
players_long = players_long.sort_values(
    ["date", "player_api_id"]
).reset_index(drop=True)

player_features_join = player_features_join.sort_values(
    ["attribute_date", "player_api_id"]
).reset_index(drop=True)

In [114]:
players_with_attributes = pd.merge_asof(
    players_long,
    player_features_join,

    left_on="date",
    right_on="attribute_date",

    by="player_api_id",

    direction="backward"
)

In [115]:
future_player_data = (
    players_with_attributes["attribute_date"]
    > players_with_attributes["date"]
).sum()

print("Future player records used:", future_player_data)

Future player records used: 0

In [116]:
print(
    "Player rows:",
    len(players_with_attributes)
)

print(
    "Missing historical overall ratings:",
    players_with_attributes["overall_rating"]
    .isnull()
    .sum()
)

Player rows: 390466
Missing historical overall ratings: 274

In [117]:
missing_player_rating_pct = (
    players_with_attributes["overall_rating"]
    .isnull()
    .mean()
    * 100
)

print(
    "Missing player attribute percentage:",
    missing_player_rating_pct
)

Missing player attribute percentage: 0.07017256304005984

In [118]:
players_with_attributes["is_goalkeeper"] = False

valid_gk = players_with_attributes.dropna(
    subset=["goalkeeper_score"]
)

gk_indices = (
    valid_gk
    .groupby(["id", "side"])["goalkeeper_score"]
    .idxmax()
)

players_with_attributes.loc[
    gk_indices,
    "is_goalkeeper"
] = True

In [119]:
players_with_attributes[
    [
        "id",
        "side",
        "player_api_id",
        "overall_rating",
        "goalkeeper_score",
        "is_goalkeeper"
    ]
].head(22)

,id,side,player_api_id,overall_rating,goalkeeper_score,is_goalkeeper
0,24918,home,25840,65.0,25.8,False
1,24918,away,25852,67.0,66.8,True
2,24918,away,25860,59.0,24.8,False
3,24918,away,25952,69.0,23.8,False
4,24918,away,26065,58.0,23.0,False
5,24918,home,30464,70.0,29.2,False
6,24918,away,38626,59.0,26.2,False
7,24918,home,41711,56.0,21.8,False
8,24918,away,42232,64.0,26.8,False
9,24918,away,67333,55.0,23.4,False
10,24918,home,67374,57.0,56.6,True
11,24918,home,92026,66.0,25.8,False
12,24918,home,92094,54.0,22.8,False
13,24918,away,95217,64.0,24.8,False
14,24918,home,114016,41.0,24.6,False
15,24918,home,114664,62.0,25.6,False
16,24918,home,114746,59.0,22.4,False
17,24918,home,140819,52.0,21.6,False
18,24918,home,149006,51.0,21.8,False
19,24918,away,173011,55.0,26.4,False
20,24918,away,176302,54.0,24.2,False
21,24918,away,197515,62.0,27.2,False

In [120]:
players_with_attributes[
    [
        "id",
        "side",
        "player_api_id",
        "overall_rating",
        "goalkeeper_score",
        "is_goalkeeper"
    ]
].head(22)

,id,side,player_api_id,overall_rating,goalkeeper_score,is_goalkeeper
0,24918,home,25840,65.0,25.8,False
1,24918,away,25852,67.0,66.8,True
2,24918,away,25860,59.0,24.8,False
3,24918,away,25952,69.0,23.8,False
4,24918,away,26065,58.0,23.0,False
5,24918,home,30464,70.0,29.2,False
6,24918,away,38626,59.0,26.2,False
7,24918,home,41711,56.0,21.8,False
8,24918,away,42232,64.0,26.8,False
9,24918,away,67333,55.0,23.4,False
10,24918,home,67374,57.0,56.6,True
11,24918,home,92026,66.0,25.8,False
12,24918,home,92094,54.0,22.8,False
13,24918,away,95217,64.0,24.8,False
14,24918,home,114016,41.0,24.6,False
15,24918,home,114664,62.0,25.6,False
16,24918,home,114746,59.0,22.4,False
17,24918,home,140819,52.0,21.6,False
18,24918,home,149006,51.0,21.8,False
19,24918,away,173011,55.0,26.4,False
20,24918,away,176302,54.0,24.2,False
21,24918,away,197515,62.0,27.2,False

In [121]:
lineup_summary = (
    players_with_attributes
    .groupby(["id", "side"])
    .agg(
        players_listed=("player_api_id", "count"),
        players_with_attributes=("overall_rating", "count"),
        avg_overall_rating=("overall_rating", "mean"),
        avg_potential=("potential", "mean"),
        goalkeeper_rating=("goalkeeper_score", "max")
    )
    .reset_index()
)

In [122]:
outfield_players = players_with_attributes[
    ~players_with_attributes["is_goalkeeper"]
].copy()

In [123]:
outfield_summary = (
    outfield_players
    .groupby(["id", "side"])
    .agg(
        avg_attack=("attack_score", "mean"),
        avg_passing=("passing_score", "mean"),
        avg_technical=("technical_score", "mean"),
        avg_pace=("pace_score", "mean"),
        avg_physical=("physical_score", "mean"),
        avg_defence=("defence_score", "mean")
    )
    .reset_index()
)

In [124]:
player_team_features = lineup_summary.merge(
    outfield_summary,
    on=["id", "side"],
    how="left"
)

In [125]:
player_team_features.head()

,id,side,players_listed,players_with_attributes,avg_overall_rating,avg_potential,goalkeeper_rating,avg_attack,avg_passing,avg_technical,avg_pace,avg_physical,avg_defence
0,518,away,11,11,70.090909,74.636364,70.4,62.175000,65.100000,64.450000,66.966667,70.125000,60.350000
1,518,home,11,11,63.818182,68.454545,67.2,58.575000,57.366667,59.000000,66.333333,64.600000,52.375000
2,519,away,10,10,64.900000,70.000000,69.6,57.777778,59.777778,59.333333,64.703704,65.527778,49.222222
3,519,home,11,11,64.181818,68.727273,69.8,53.750000,57.900000,55.750000,68.533333,66.675000,52.475000
4,520,away,10,10,68.200000,71.800000,70.4,61.388889,61.962963,61.444444,66.444444,68.777778,55.666667

In [126]:
player_team_features_wide = (
    player_team_features
    .pivot(
        index="id",
        columns="side"
    )
)

In [127]:
player_team_features_wide.columns = [
    f"{side}_{feature}"
    for feature, side in player_team_features_wide.columns
]

In [128]:
player_team_features_wide = (
    player_team_features_wide
    .reset_index()
)

In [129]:
player_team_features_wide.head()

,id,away_players_listed,home_players_listed,away_players_with_attributes,home_players_with_attributes,away_avg_overall_rating,home_avg_overall_rating,away_avg_potential,home_avg_potential,away_goalkeeper_rating,...,away_avg_passing,home_avg_passing,away_avg_technical,home_avg_technical,away_avg_pace,home_avg_pace,away_avg_physical,home_avg_physical,away_avg_defence,home_avg_defence
0,518,11,11,11,11,70.090909,63.818182,74.636364,68.454545,70.4,...,65.100000,57.366667,64.450000,59.000000,66.966667,66.333333,70.125000,64.600000,60.350000,52.375000
1,519,10,11,10,11,64.900000,64.181818,70.000000,68.727273,69.6,...,59.777778,57.900000,59.333333,55.750000,64.703704,68.533333,65.527778,66.675000,49.222222,52.475000
2,520,10,11,10,11,68.200000,64.545455,71.800000,69.909091,70.4,...,61.962963,58.233333,61.444444,60.450000,66.444444,65.500000,68.777778,63.775000,55.666667,52.825000
3,522,11,10,11,10,64.181818,70.000000,69.181818,77.200000,66.0,...,57.666667,62.740741,55.550000,64.777778,67.366667,70.777778,65.800000,66.916667,52.675000,58.527778
4,523,10,11,10,11,62.000000,64.000000,67.400000,67.909091,51.0,...,58.481481,61.366667,60.777778,55.650000,63.703704,62.866667,62.777778,65.400000,51.500000,56.825000

In [130]:
model_data = model_data.merge(
    player_team_features_wide,
    on="id",
    how="left"
)

In [131]:
print("Rows:", len(model_data))
print(
    "Duplicate match IDs:",
    model_data["id"].duplicated().sum()
)

Rows: 18016
Duplicate match IDs: 0

In [132]:
print(
    model_data[
        [
            "home_players_with_attributes",
            "away_players_with_attributes"
        ]
    ].describe()
)

       home_players_with_attributes  away_players_with_attributes
count                  18016.000000                  18016.000000
mean                      10.830373                     10.827709
std                        0.769731                      0.780885
min                        2.000000                      2.000000
25%                       11.000000                     11.000000
50%                       11.000000                     11.000000
75%                       11.000000                     11.000000
max                       11.000000                     11.000000

In [133]:
print(
    "Missing home player rating:",
    model_data["home_avg_overall_rating"]
    .isnull()
    .sum()
)

print(
    "Missing away player rating:",
    model_data["away_avg_overall_rating"]
    .isnull()
    .sum()
)

Missing home player rating: 0
Missing away player rating: 0

In [134]:
print(
    "Matches with fewer than 8 rated home players:",
    (
        model_data["home_players_with_attributes"] < 8
    ).sum()
)

print(
    "Matches with fewer than 8 rated away players:",
    (
        model_data["away_players_with_attributes"] < 8
    ).sum()
)

Matches with fewer than 8 rated home players: 274
Matches with fewer than 8 rated away players: 288

In [135]:
low_player_coverage = (
    (model_data["home_players_with_attributes"] < 8)
    |
    (model_data["away_players_with_attributes"] < 8)
)

print("Matches with insufficient player coverage:", low_player_coverage.sum())

print(
    "Percentage:",
    low_player_coverage.mean() * 100
)

Matches with insufficient player coverage: 407
Percentage: 2.259103019538188

In [136]:
model_data = model_data[
    ~low_player_coverage
].copy()

print("Rows remaining:", len(model_data))
print("Duplicate match IDs:", model_data["id"].duplicated().sum())

Rows remaining: 17609
Duplicate match IDs: 0

In [137]:
model_data["target"].value_counts(normalize=True) * 100

target
Home Win    45.578965
Away Win    29.115793
Draw        25.305242
Name: proportion, dtype: float64

### Player attribute coverage decision

Historical player attributes were matched to each player using the latest available attribute record before the match date.

Most matches had very strong player-data coverage. The median number of players with available historical attributes was 11 for both home and away teams, with an average of approximately 10.83 players per team.

A small number of matches contained very limited player information. To ensure that aggregated team-level player features were based on a reasonable portion of the lineup, matches were required to have historical attributes for at least 8 players on both teams.

Matches below this threshold were removed rather than estimating large portions of the lineup.

Player features were aggregated into team-level measures such as overall rating, attacking ability, passing, technical ability, pace, physical ability, defence and goalkeeper strength.

In [138]:
model_data["overall_rating_diff"] = (
    model_data["home_avg_overall_rating"]
    - model_data["away_avg_overall_rating"]
)

model_data["potential_diff"] = (
    model_data["home_avg_potential"]
    - model_data["away_avg_potential"]
)

model_data["attack_diff"] = (
    model_data["home_avg_attack"]
    - model_data["away_avg_attack"]
)

model_data["passing_diff"] = (
    model_data["home_avg_passing"]
    - model_data["away_avg_passing"]
)

model_data["technical_diff"] = (
    model_data["home_avg_technical"]
    - model_data["away_avg_technical"]
)

model_data["pace_diff"] = (
    model_data["home_avg_pace"]
    - model_data["away_avg_pace"]
)

model_data["physical_diff"] = (
    model_data["home_avg_physical"]
    - model_data["away_avg_physical"]
)

model_data["defence_diff"] = (
    model_data["home_avg_defence"]
    - model_data["away_avg_defence"]
)

model_data["goalkeeper_diff"] = (
    model_data["home_goalkeeper_rating"]
    - model_data["away_goalkeeper_rating"]
)

In [139]:
model_data["form_points_diff"] = (
    model_data["home_form_points_5"]
    - model_data["away_form_points_5"]
)

model_data["recent_goals_scored_diff"] = (
    model_data["home_avg_goals_scored_5"]
    - model_data["away_avg_goals_scored_5"]
)

model_data["recent_goals_conceded_diff"] = (
    model_data["home_avg_goals_conceded_5"]
    - model_data["away_avg_goals_conceded_5"]
)

In [140]:
model_data["buildUpPlaySpeed_diff"] = (
    model_data["home_buildUpPlaySpeed"]
    - model_data["away_buildUpPlaySpeed"]
)

model_data["buildUpPlayPassing_diff"] = (
    model_data["home_buildUpPlayPassing"]
    - model_data["away_buildUpPlayPassing"]
)

model_data["chanceCreationPassing_diff"] = (
    model_data["home_chanceCreationPassing"]
    - model_data["away_chanceCreationPassing"]
)

model_data["chanceCreationCrossing_diff"] = (
    model_data["home_chanceCreationCrossing"]
    - model_data["away_chanceCreationCrossing"]
)

model_data["chanceCreationShooting_diff"] = (
    model_data["home_chanceCreationShooting"]
    - model_data["away_chanceCreationShooting"]
)

model_data["defencePressure_diff"] = (
    model_data["home_defencePressure"]
    - model_data["away_defencePressure"]
)

model_data["defenceAggression_diff"] = (
    model_data["home_defenceAggression"]
    - model_data["away_defenceAggression"]
)

model_data["defenceTeamWidth_diff"] = (
    model_data["home_defenceTeamWidth"]
    - model_data["away_defenceTeamWidth"]
)

In [141]:
difference_columns = [
    "overall_rating_diff",
    "attack_diff",
    "passing_diff",
    "defence_diff",
    "goalkeeper_diff",
    "form_points_diff",
    "recent_goals_scored_diff",
    "recent_goals_conceded_diff"
]

model_data[
    [
        "home_team_name",
        "away_team_name"
    ] + difference_columns + ["target"]
].head(10)

,home_team_name,away_team_name,overall_rating_diff,attack_diff,passing_diff,defence_diff,goalkeeper_diff,form_points_diff,recent_goals_scored_diff,recent_goals_conceded_diff,target
0,Grasshopper Club Zürich,Neuchâtel Xamax,-3.000000,-6.800000,-3.400000,-2.241667,-10.2,5.0,0.6,-2.0,Draw
1,AC Bellinzona,FC Sion,-3.000000,-5.200000,-5.233333,-3.875000,-9.2,1.0,-0.6,-0.2,Away Win
2,FC Luzern,FC St. Gallen,2.090909,4.150000,4.466667,-2.200000,0.4,10.0,1.8,-2.0,Home Win
3,FC Basel,FC Zürich,3.454545,0.800000,2.966667,9.200000,1.0,8.0,1.2,-1.8,Home Win
4,FC Sion,FC Basel,-4.727273,-2.525000,-3.966667,-6.775000,-4.4,-6.0,-1.2,1.0,Away Win
5,BSC Young Boys,FC Luzern,3.545455,-3.475000,-1.100000,9.850000,7.0,-6.0,-1.6,1.6,Draw
6,FC St. Gallen,AC Bellinzona,-0.545455,2.800000,-2.500000,-1.725000,7.2,-1.0,0.4,1.0,Home Win
7,FC Zürich,Grasshopper Club Zürich,4.163636,6.338889,7.629630,1.100000,6.4,-3.0,-0.4,1.6,Home Win
8,Standard de Liège,SV Zulte-Waregem,5.818182,6.566667,5.074074,5.852778,4.0,0.0,-0.2,0.2,Draw
9,KV Kortrijk,Club Brugge KV,-6.272727,-3.600000,-7.733333,-7.975000,-3.2,0.0,0.2,0.0,Home Win

In [142]:
from pathlib import Path

Path("data/processed").mkdir(parents=True, exist_ok=True)

model_data.to_csv(
    "data/processed/model_data_engineered.csv",
    index=False
)

print(model_data.shape)

(17609, 156)

In [143]:
feature_audit = pd.DataFrame({
    "column": model_data.columns,
    "dtype": model_data.dtypes.astype(str).values,
    "missing": model_data.isnull().sum().values,
    "missing_pct": (
        model_data.isnull().mean().values * 100
    ),
    "unique_values": [
        model_data[col].nunique()
        for col in model_data.columns
    ]
})

feature_audit

                          column    dtype  missing  missing_pct  unique_values
0                             id    int64        0          0.0          17609
1                     country_id    int64        0          0.0             11
2                      league_id    int64        0          0.0             11
3                         season      str        0          0.0              6
4                          stage    int64        0          0.0             38
..                           ...      ...      ...          ...            ...
151  chanceCreationCrossing_diff  float64        0          0.0            103
152  chanceCreationShooting_diff  float64        0          0.0            100
153         defencePressure_diff  float64        0          0.0             84
154       defenceAggression_diff  float64        0          0.0             81
155        defenceTeamWidth_diff  float64        0          0.0             75

[156 rows x 5 columns]

In [144]:
print("Total columns:", len(model_data.columns))

for i, col in enumerate(model_data.columns):
    print(i, col)

Total columns: 156
0 id
1 country_id
2 league_id
3 season
4 stage
5 date
6 match_api_id
7 home_team_api_id
8 away_team_api_id
9 home_team_goal
10 away_team_goal
11 home_player_X1
12 home_player_X2
13 home_player_X3
14 home_player_X4
15 home_player_X5
16 home_player_X6
17 home_player_X7
18 home_player_X8
19 home_player_X9
20 home_player_X10
21 home_player_X11
22 away_player_X1
23 away_player_X2
24 away_player_X3
25 away_player_X4
26 away_player_X5
27 away_player_X6
28 away_player_X7
29 away_player_X8
30 away_player_X9
31 away_player_X10
32 away_player_X11
33 home_player_Y1
34 home_player_Y2
35 home_player_Y3
36 home_player_Y4
37 home_player_Y5
38 home_player_Y6
39 home_player_Y7
40 home_player_Y8
41 home_player_Y9
42 home_player_Y10
43 home_player_Y11
44 away_player_Y1
45 away_player_Y2
46 away_player_Y3
47 away_player_Y4
48 away_player_Y5
49 away_player_Y6
50 away_player_Y7
51 away_player_Y8
52 away_player_Y9
53 away_player_Y10
54 away_player_Y11
55 home_player_1
56 home_player_2
57 home_player_3
58 home_player_4
59 home_player_5
60 home_player_6
61 home_player_7
62 home_player_8
63 home_player_9
64 home_player_10
65 home_player_11
66 away_player_1
67 away_player_2
68 away_player_3
69 away_player_4
70 away_player_5
71 away_player_6
72 away_player_7
73 away_player_8
74 away_player_9
75 away_player_10
76 away_player_11
77 target
78 country_name
79 league_name
80 home_team_name
81 away_team_name
82 home_team_attr_date
83 home_buildUpPlaySpeed
84 home_buildUpPlayPassing
85 home_buildUpPlayDribblingClass
86 home_buildUpPlayPositioningClass
87 home_chanceCreationPassing
88 home_chanceCreationCrossing
89 home_chanceCreationShooting
90 home_chanceCreationPositioningClass
91 home_defencePressure
92 home_defenceAggression
93 home_defenceTeamWidth
94 home_defenceDefenderLineClass
95 away_team_attr_date
96 away_buildUpPlaySpeed
97 away_buildUpPlayPassing
98 away_buildUpPlayDribblingClass
99 away_buildUpPlayPositioningClass
100 away_chanceCreationPassing
101 away_chanceCreationCrossing
102 away_chanceCreationShooting
103 away_chanceCreationPositioningClass
104 away_defencePressure
105 away_defenceAggression
106 away_defenceTeamWidth
107 away_defenceDefenderLineClass
108 home_form_points_5
109 home_avg_goals_scored_5
110 home_avg_goals_conceded_5
111 away_form_points_5
112 away_avg_goals_scored_5
113 away_avg_goals_conceded_5
114 away_players_listed
115 home_players_listed
116 away_players_with_attributes
117 home_players_with_attributes
118 away_avg_overall_rating
119 home_avg_overall_rating
120 away_avg_potential
121 home_avg_potential
122 away_goalkeeper_rating
123 home_goalkeeper_rating
124 away_avg_attack
125 home_avg_attack
126 away_avg_passing
127 home_avg_passing
128 away_avg_technical
129 home_avg_technical
130 away_avg_pace
131 home_avg_pace
132 away_avg_physical
133 home_avg_physical
134 away_avg_defence
135 home_avg_defence
136 overall_rating_diff
137 potential_diff
138 attack_diff
139 passing_diff
140 technical_diff
141 pace_diff
142 physical_diff
143 defence_diff
144 goalkeeper_diff
145 form_points_diff
146 recent_goals_scored_diff
147 recent_goals_conceded_diff
148 buildUpPlaySpeed_diff
149 buildUpPlayPassing_diff
150 chanceCreationPassing_diff
151 chanceCreationCrossing_diff
152 chanceCreationShooting_diff
153 defencePressure_diff
154 defenceAggression_diff
155 defenceTeamWidth_diff

In [145]:
identifier_columns = [
    "id",
    "match_api_id",
    "country_id",
    "league_id",
    "home_team_api_id",
    "away_team_api_id"
]

In [146]:
leakage_columns = [
    "home_team_goal",
    "away_team_goal"
]

In [147]:
post_match_columns = [
    "goal",
    "shoton",
    "shotoff",
    "foulcommit",
    "card",
    "cross",
    "corner",
    "possession"
]

In [148]:
metadata_columns = [
    "date",
    "country_name",
    "home_team_name",
    "away_team_name"
]

In [149]:
player_id_columns = [
    f"home_player_{i}" for i in range(1, 12)
] + [
    f"away_player_{i}" for i in range(1, 12)
]

In [150]:
player_position_columns = [
    col for col in model_data.columns
    if "player_X" in col or "player_Y" in col
]

In [151]:
attribute_date_columns = [
    "home_team_attr_date",
    "away_team_attr_date"
]

In [152]:
categorical_features = [
    "league_name",

    "home_buildUpPlayDribblingClass",
    "away_buildUpPlayDribblingClass",

    "home_buildUpPlayPositioningClass",
    "away_buildUpPlayPositioningClass",

    "home_chanceCreationPositioningClass",
    "away_chanceCreationPositioningClass",

    "home_defenceDefenderLineClass",
    "away_defenceDefenderLineClass"
]

In [153]:
columns_to_exclude = (
    identifier_columns
    + leakage_columns
    + post_match_columns
    + metadata_columns
    + player_id_columns
    + player_position_columns
    + attribute_date_columns
)

In [154]:
columns_to_exclude = [
    col for col in columns_to_exclude
    if col in model_data.columns
]

In [155]:
X_candidate = model_data.drop(
    columns=columns_to_exclude + ["target"],
    errors="ignore"
).copy()

y = model_data["target"].copy()

In [156]:
print("Candidate feature shape:", X_candidate.shape)

print("\nCandidate features:")
for col in X_candidate.columns:
    print(col)

Candidate feature shape: (17609, 75)

Candidate features:
season
stage
league_name
home_buildUpPlaySpeed
home_buildUpPlayPassing
home_buildUpPlayDribblingClass
home_buildUpPlayPositioningClass
home_chanceCreationPassing
home_chanceCreationCrossing
home_chanceCreationShooting
home_chanceCreationPositioningClass
home_defencePressure
home_defenceAggression
home_defenceTeamWidth
home_defenceDefenderLineClass
away_buildUpPlaySpeed
away_buildUpPlayPassing
away_buildUpPlayDribblingClass
away_buildUpPlayPositioningClass
away_chanceCreationPassing
away_chanceCreationCrossing
away_chanceCreationShooting
away_chanceCreationPositioningClass
away_defencePressure
away_defenceAggression
away_defenceTeamWidth
away_defenceDefenderLineClass
home_form_points_5
home_avg_goals_scored_5
home_avg_goals_conceded_5
away_form_points_5
away_avg_goals_scored_5
away_avg_goals_conceded_5
away_players_listed
home_players_listed
away_players_with_attributes
home_players_with_attributes
away_avg_overall_rating
home_avg_overall_rating
away_avg_potential
home_avg_potential
away_goalkeeper_rating
home_goalkeeper_rating
away_avg_attack
home_avg_attack
away_avg_passing
home_avg_passing
away_avg_technical
home_avg_technical
away_avg_pace
home_avg_pace
away_avg_physical
home_avg_physical
away_avg_defence
home_avg_defence
overall_rating_diff
potential_diff
attack_diff
passing_diff
technical_diff
pace_diff
physical_diff
defence_diff
goalkeeper_diff
form_points_diff
recent_goals_scored_diff
recent_goals_conceded_diff
buildUpPlaySpeed_diff
buildUpPlayPassing_diff
chanceCreationPassing_diff
chanceCreationCrossing_diff
chanceCreationShooting_diff
defencePressure_diff
defenceAggression_diff
defenceTeamWidth_diff

In [157]:
missing_final = (
    X_candidate
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_final[missing_final > 0]

Series([], dtype: int64)

In [158]:
missing_final_pct = (
    X_candidate
    .isnull()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_final_pct[
    missing_final_pct > 0
]

Series([], dtype: float64)

### Final missing-value check

The candidate modelling dataset contains no remaining missing values after the data integration, historical matching, feature engineering and coverage filtering steps.

This means the dataset is ready to move into exploratory data analysis and later preprocessing/model development.

In [159]:
print("Final engineered dataset shape:", model_data.shape)
print("Candidate feature shape:", X_candidate.shape)

print(
    "Duplicate match IDs:",
    model_data["id"].duplicated().sum()
)

print(
    "\nTarget distribution:"
)

print(
    model_data["target"]
    .value_counts(normalize=True)
    .mul(100)
)

Final engineered dataset shape: (17609, 156)
Candidate feature shape: (17609, 75)
Duplicate match IDs: 0

Target distribution:
target
Home Win    45.578965
Away Win    29.115793
Draw        25.305242
Name: proportion, dtype: float64

In [160]:
feature_audit = pd.DataFrame({
    "feature": X_candidate.columns,
    "dtype": X_candidate.dtypes.astype(str).values,
    "missing_count": X_candidate.isnull().sum().values,
    "missing_percentage": (
        X_candidate.isnull().mean().mul(100).values
    ),
    "unique_values": [
        X_candidate[col].nunique()
        for col in X_candidate.columns
    ]
})

feature_audit.head(20)

,feature,dtype,missing_count,missing_percentage,unique_values
0,season,str,0,0.0,6
1,stage,int64,0,0.0,38
2,league_name,str,0,0.0,11
3,home_buildUpPlaySpeed,float64,0,0.0,56
4,home_buildUpPlayPassing,float64,0,0.0,57
5,home_buildUpPlayDribblingClass,str,0,0.0,3
6,home_buildUpPlayPositioningClass,str,0,0.0,2
7,home_chanceCreationPassing,float64,0,0.0,50
8,home_chanceCreationCrossing,float64,0,0.0,55
9,home_chanceCreationShooting,float64,0,0.0,56
10,home_chanceCreationPositioningClass,str,0,0.0,2
11,home_defencePressure,float64,0,0.0,48
12,home_defenceAggression,float64,0,0.0,45
13,home_defenceTeamWidth,float64,0,0.0,42
14,home_defenceDefenderLineClass,str,0,0.0,2
15,away_buildUpPlaySpeed,float64,0,0.0,56
16,away_buildUpPlayPassing,float64,0,0.0,57
17,away_buildUpPlayDribblingClass,str,0,0.0,3
18,away_buildUpPlayPositioningClass,str,0,0.0,2
19,away_chanceCreationPassing,float64,0,0.0,50

In [161]:
from pathlib import Path

Path("data/processed").mkdir(
    parents=True,
    exist_ok=True
)

Path("outputs/tables").mkdir(
    parents=True,
    exist_ok=True
)

Path("outputs/figures").mkdir(
    parents=True,
    exist_ok=True
)

In [162]:
model_data.to_csv(
    "data/processed/model_data_engineered.csv",
    index=False
)

In [168]:
feature_audit.to_csv(
    "/Users/sasanda/Documents/GitHub/european-soccer-machine-learning/outputs/tables/dataset_summary.csv",
    index=False
)

In [166]:
dataset_summary = pd.DataFrame({
    "metric": [
        "Number of matches",
        "Candidate ML features",
        "Duplicate match IDs",
        "Missing candidate values",
        "Home Win %",
        "Away Win %",
        "Draw %"
    ],
    "value": [
        len(model_data),
        X_candidate.shape[1],
        model_data["id"].duplicated().sum(),
        X_candidate.isnull().sum().sum(),
        (
            model_data["target"]
            .eq("Home Win")
            .mean() * 100
        ),
        (
            model_data["target"]
            .eq("Away Win")
            .mean() * 100
        ),
        (
            model_data["target"]
            .eq("Draw")
            .mean() * 100
        )
    ]
})

dataset_summary

                     metric         value
0         Number of matches  17609.000000
1     Candidate ML features     75.000000
2       Duplicate match IDs      0.000000
3  Missing candidate values      0.000000
4                Home Win %     45.578965
5                Away Win %     29.115793
6                    Draw %     25.305242

In [169]:
dataset_summary.to_csv(
    "/Users/sasanda/Documents/GitHub/european-soccer-machine-learning/outputs/tables/dataset_summary.csv",
    index=False
)